sdk:
  port: 6060
  userName: "admin"
  password: "HuaWei123"
  localhost: 192.168.141.222
server:
  port: 22233
spring:
  profiles:
    active: dev
    include: common
  application:
    name: "cbb-nb-smart-lock"
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db
    encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:com/summit/dao/*.xml
  config-location: classpath:mybatis-config.xml

nbLock:
  baseUrl: http://47.106.35.122:8088/intf/
