sdk:
  appId: 17708825
  apiKey: gT9AW413oU3mS2G2tGSuX1iG
  secretKey: 9lvVAufG1Auwg6iaYnoVET2Spd06hNYl
  groupId: nb_smart
server:
  port: 22233
spring:
  profiles:
    active: pro
    include: common
  application:
    name: "cbb-nb-smart-lock"
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db
    encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:com/summit/dao/**/*.xml
  config-location: classpath:mybatis-config.xml

nbLock:
  baseUrl: http://47.106.35.122:8088/intf/
