version: '2'
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    image: ${projectName}/backend:1.0
    restart: always
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./logs:/opt/App/logs
      - /home/nb_smart_lock_backend/snapshot:/opt/App/snapshot
    user: root